[project]
name = "mandulabot"
version = "0.1.0"
description = "Telegram bot for Mandula requests"
authors = ["EvgeniyFerz <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.0",
    "python-dotenv",
    "flask",
    "requests>=2.31.0"
]
