name: Keep Alive Ping
on:
  schedule:
    - cron: '*/5 * * * *'  # Каждые 5 минут
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2  # Ждём до 2 минут ответа
    steps:
      - name: Ping Render Bot
        run: |
          # Ждём ответа до 60 секунд и проверяем код 200
          curl --retry 3 --retry-delay 5 --max-time 60 --fail "https://mandulabot-t5op.onrender.com"
