name: Keep Alive Ping
on:
  schedule:
    - cron: '*/5 * * * *'  # Каждые 5 минут
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Ping Render Bot
        run: |
          response_code=$(curl -s -o /dev/null -w "%{http_code}" --max-time 30 "https://mandulabot.onrender.com/health")
          if [ "$response_code" -eq 200 ]; then
            echo "✅ Bot is alive and responding"
          else
            echo "❌ Bot is not responding properly. HTTP Code: $response_code"
            exit 1
          fi
